### PR TITLE
wreck everything

### PR DESCRIPTION
**Pull request by antonagestam**
https://www.debuggex.com/r/PGtbIzDBXnPRPLa5

### CODE REVIEW

**Comment by JoelRoxell** [comment]
Hey, appreciate the effort. I'll merge your changes as soon as you've rebased appropriately ;). Additionally, do you have any idea to make the regex parse supplementary lines (if they are started with `#`) after the initial TODO?

**Comment by sebbekarlsson** [comment]
> Hey, appreciate the effort. I'll merge your changes as soon as you've rebased appropriately ;). Additionally, do you have any idea to make the regex parse supplementary lines (if they're started with `#`) after the initial TODO?

If one would do this using a lexer instead of regex, it would be super-easy.

**Comment by JoelRoxell** [comment]
@sebbekarlsson Well be my guest m8.

**Comment by antonagestam** [comment]
You could achieve that by using `re.MULTILINE` and appending a group to the regex that matches on e.g.`\n\s*//\s*#`. I was mainly interested in showing that you can split up this problem into small composable parts using generators.

I agree with @sebbekarlsson that the only sane way  to do actual correct parsing  is with a lexer.

**Comment by sebbekarlsson** [comment]
really cool approach @antonagestam , I liked it!

**Pull request closed without merging**
